# -*- coding: utf-8 -*-
"""mavoix_OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pf-u71RN8iKlsh7s7y8iv5Wj5JDnRVNv
"""

!sudo apt install tesseract-ocr
!sudo apt install libtesseract-dev
!pip install pytesseract

!git clone https://github.com/Sdccoding/sandbox.git

cd sandbox/ml-dl-ds/assignment_v3/data-set/

ls

import pytesseract
import cv2
from PIL import Image
#Reading the image
#img = Image.open('ms-7.jpg')
#img.save('Foto.png')
img = cv2.imread('ms-7.jpg') #In this step read image from user.

# Adding custom options
custom_config = r'--oem 3 --psm 6'
#Converting the image to string
strg = pytesseract.image_to_string(img, config=custom_config)
#Printing the string
#print(strg)

#cv2.imshow('dst_rt', img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

#Finding the index where the subjects are beginning
m1_index= strg.find('MATHEMATICS')
m2_index=strg.find('maTHenaTics')
m3_index=strg.find('naTHenarics')
if m1_index!=-1:
  m_index=m1_index
elif m2_index!=-1:
  m_index=m1_index
else:
 m_index=m2_index

p_index= strg.find('PHYSICS')
c_index= strg.find('CHEMISTRY')
'''print(m_index)
print(p_index)
print(c_index)'''

#Storing the substring from beginning indexes of each line 
m_main = strg[m_index:m_index+43]
p_main = strg[p_index:p_index+40]
c_main = strg[c_index:c_index+40]
'''print(m_main)
print(p_main)
print(c_main)'''

import re
#Only storing the integers from the above string
m_int = re.findall(r'\d+',m_main) 
p_int = re.findall(r'\d+',p_main) 
c_int = re.findall(r'\d+',c_main) 
'''print(m_int)
print(p_int)
print(c_int)'''

for i in range(len(m_int)):
  if int(m_int[i])>100:
    m_int[i]=0
for i in range(len(p_int)):
  if int(p_int[i])>100:
    p_int[i]=0
for i in range(len(c_int)):
  if int(c_int[i]) > 100:
    c_int[i]=0
'''print(m_int)
print(p_int)
print(c_int)'''

if (len(m_int)==0) or (len(p_int)==0) or len(c_int)==0 :
  print("Upload a clear image")
  exit()

#Finding the maximum value amongst the int values,after putting them in a list 
m = max(list(map(int,m_int )))
p = max(list(map(int,p_int)))
c = max(list(map(int,c_int)))
pcm=round((m+p+c)/3,2)
print(pcm," ",m," ",p," ",c)
#Printing his average marks rounded off to 2 positions,maths,physics and Chemistry marks.

if pcm>=90:
  print("Campus Alpha is recommended")
elif pcm>=80:
  print("Campus Beta is recommended")
elif pcm>=70:
  print("Campus Gamma is recommended")
else:
  print("You are not eligible for any of the campusses")

